// 获取塔罗牌图片路径的辅助函数
export function getTarotCardImage(cardName: string): string {
  // 中文名到文件名的映射
  const chineseMapping = {
    "愚者": "the fool.jpg",
    "魔术师": "THE MAGICIAN..jpg",
    "女祭司": "THE HIGH PRIESTESS.jpg",
    "皇后": "THE EMPRESS..jpg",
    "皇帝": "THE EMPEROR..jpg",
    "教皇": "THE HIEROPHANT.jpg",
    "恋人": "THE LOVERS..jpg",
    "战车": "THE CHARIOT..jpg",
    "力量": "STRENGTH..jpg",
    "隐者": "THE HERMIT..jpg",
    "命运之轮": "WHEEL • FORTUNE.jpg",
    "正义": "TUSTICE ..jpg",
    "倒吊人": "THE HANGED MAN..jpg",
    "死神": "DEATH..jpg",
    "节制": "TEMPERANCE..jpg",
    "恶魔": "THE DEVIL •.jpg",
    "高塔": "THE TOWER..jpg",
    "星星": "THE STAR..jpg",
    "月亮": "THE MOON.jpg",
    "太阳": "THE SUN.jpg",
    "审判": "JUDGEMENT..jpg",
    "世界": "THE VYORLD..jpg",
    "权杖王牌": "w01.jpg",
    "权杖二": "w02.jpg",
    "权杖三": "w03.jpg",
    "权杖四": "w04.jpg",
    "权杖五": "w05.jpg",
    "权杖六": "w06.jpg",
    "权杖七": "w07.jpg",
    "权杖八": "w08.jpg",
    "权杖九": "w09.jpg",
    "权杖十": "w10.jpg",
    "权杖侍从": "w11.jpg",
    "权杖骑士": "w12.jpg",
    "权杖王后": "w13.jpg",
    "权杖国王": "w14.jpg",
    "圣杯王牌": "c01.jpg",
    "圣杯二": "c02.jpg",
    "圣杯三": "c03.jpg",
    "圣杯四": "c04.jpg",
    "圣杯五": "c05.jpg",
    "圣杯六": "c06.jpg",
    "圣杯七": "c07.jpg",
    "圣杯八": "c08.jpg",
    "圣杯九": "c09.jpg",
    "圣杯十": "c10.jpg",
    "圣杯侍从": "c11.jpg",
    "圣杯骑士": "c12.jpg",
    "圣杯王后": "c13.jpg",
    "圣杯国王": "c14.jpg",
    "宝剑王牌": "s01.jpg",
    "宝剑二": "s02.jpg",
    "宝剑三": "s03.jpg",
    "宝剑四": "s04.jpg",
    "宝剑五": "s05.jpg",
    "宝剑六": "s06.jpg",
    "宝剑七": "s07.jpg",
    "宝剑八": "s08.jpg",
    "宝剑九": "s09.jpg",
    "宝剑十": "s10.jpg",
    "宝剑侍从": "s11.jpg",
    "宝剑骑士": "s12.jpg",
    "宝剑王后": "s13.jpg",
    "宝剑国王": "s14.jpg",
    "星币王牌": "p01.jpg",
    "星币二": "p02.jpg",
    "星币三": "p03.jpg",
    "星币四": "p04.jpg",
    "星币五": "p05.jpg",
    "星币六": "p06.jpg",
    "星币七": "p07.jpg",
    "星币八": "p08.jpg",
    "星币九": "p09.jpg",
    "星币十": "p10.jpg",
    "星币侍从": "p11.jpg",
    "星币骑士": "p12.jpg",
    "星币王后": "p13.jpg",
    "星币国王": "p14.jpg"
  };

  // 英文名到文件名的映射
  const englishMapping = {
    "The Fool": "the fool.jpg",
    "The Magician": "THE MAGICIAN..jpg",
    "The High Priestess": "THE HIGH PRIESTESS.jpg",
    "The Empress": "THE EMPRESS..jpg",
    "The Emperor": "THE EMPEROR..jpg",
    "The Hierophant": "THE HIEROPHANT.jpg",
    "The Lovers": "THE LOVERS..jpg",
    "The Chariot": "THE CHARIOT..jpg",
    "Strength": "STRENGTH..jpg",
    "The Hermit": "THE HERMIT..jpg",
    "Wheel of Fortune": "WHEEL • FORTUNE.jpg",
    "Justice": "TUSTICE ..jpg",
    "The Hanged Man": "THE HANGED MAN..jpg",
    "Death": "DEATH..jpg",
    "Temperance": "TEMPERANCE..jpg",
    "The Devil": "THE DEVIL •.jpg",
    "The Tower": "THE TOWER..jpg",
    "The Star": "THE STAR..jpg",
    "The Moon": "THE MOON.jpg",
    "The Sun": "THE SUN.jpg",
    "Judgement": "JUDGEMENT..jpg",
    "The World": "THE VYORLD..jpg",
    "Ace of Wands": "w01.jpg",
    "Two of Wands": "w02.jpg",
    "Three of Wands": "w03.jpg",
    "Four of Wands": "w04.jpg",
    "Five of Wands": "w05.jpg",
    "Six of Wands": "w06.jpg",
    "Seven of Wands": "w07.jpg",
    "Eight of Wands": "w08.jpg",
    "Nine of Wands": "w09.jpg",
    "Ten of Wands": "w10.jpg",
    "Page of Wands": "w11.jpg",
    "Knight of Wands": "w12.jpg",
    "Queen of Wands": "w13.jpg",
    "King of Wands": "w14.jpg",
    "Ace of Cups": "c01.jpg",
    "Two of Cups": "c02.jpg",
    "Three of Cups": "c03.jpg",
    "Four of Cups": "c04.jpg",
    "Five of Cups": "c05.jpg",
    "Six of Cups": "c06.jpg",
    "Seven of Cups": "c07.jpg",
    "Eight of Cups": "c08.jpg",
    "Nine of Cups": "c09.jpg",
    "Ten of Cups": "c10.jpg",
    "Page of Cups": "c11.jpg",
    "Knight of Cups": "c12.jpg",
    "Queen of Cups": "c13.jpg",
    "King of Cups": "c14.jpg",
    "Ace of Swords": "s01.jpg",
    "Two of Swords": "s02.jpg",
    "Three of Swords": "s03.jpg",
    "Four of Swords": "s04.jpg",
    "Five of Swords": "s05.jpg",
    "Six of Swords": "s06.jpg",
    "Seven of Swords": "s07.jpg",
    "Eight of Swords": "s08.jpg",
    "Nine of Swords": "s09.jpg",
    "Ten of Swords": "s10.jpg",
    "Page of Swords": "s11.jpg",
    "Knight of Swords": "s12.jpg",
    "Queen of Swords": "s13.jpg",
    "King of Swords": "s14.jpg",
    "Ace of Pentacles": "p01.jpg",
    "Two of Pentacles": "p02.jpg",
    "Three of Pentacles": "p03.jpg",
    "Four of Pentacles": "p04.jpg",
    "Five of Pentacles": "p05.jpg",
    "Six of Pentacles": "p06.jpg",
    "Seven of Pentacles": "p07.jpg",
    "Eight of Pentacles": "p08.jpg",
    "Nine of Pentacles": "p09.jpg",
    "Ten of Pentacles": "p10.jpg",
    "Page of Pentacles": "p11.jpg",
    "Knight of Pentacles": "p12.jpg",
    "Queen of Pentacles": "p13.jpg",
    "King of Pentacles": "p14.jpg"
  };

  // 先尝试中文映射
  let filename = chineseMapping[cardName as keyof typeof chineseMapping];
  
  // 如果中文映射找不到，尝试英文映射
  if (!filename) {
    filename = englishMapping[cardName as keyof typeof englishMapping];
  }
  
  // 如果还是找不到，尝试数字格式转换（如 "4 of Pentacles" -> "Four of Pentacles"）
  if (!filename && /^\d+ of /.test(cardName)) {
    const numberWords = {
      '1': 'Ace', '2': 'Two', '3': 'Three', '4': 'Four', '5': 'Five',
      '6': 'Six', '7': 'Seven', '8': 'Eight', '9': 'Nine', '10': 'Ten',
      '11': 'Page', '12': 'Knight', '13': 'Queen', '14': 'King'
    };
    
    const match = cardName.match(/^(\d+) of (.+)$/);
    if (match) {
      const [, number, suit] = match;
      const wordNumber = numberWords[number as keyof typeof numberWords];
      if (wordNumber) {
        const convertedName = `${wordNumber} of ${suit}`;
        filename = englishMapping[convertedName as keyof typeof englishMapping];
      }
    }
  }
  
  return filename ? `/images/tarot-cards/${encodeURIComponent(filename)}` : '/images/tarot-cards/cardback.png';
}

// 获取所有可用的塔罗牌图片
export function getAllTarotCardImages(): Record<string, string> {
  const mapping = {
  "愚者": "the fool.jpg",
  "魔术师": "THE MAGICIAN..jpg",
  "女祭司": "THE HIGH PRIESTESS.jpg",
  "皇后": "THE EMPRESS..jpg",
  "皇帝": "THE EMPEROR..jpg",
  "教皇": "THE HIEROPHANT.jpg",
  "恋人": "THE LOVERS..jpg",
  "战车": "THE CHARIOT..jpg",
  "力量": "STRENGTH..jpg",
  "隐者": "THE HERMIT..jpg",
  "命运之轮": "WHEEL • FORTUNE.jpg",
  "正义": "TUSTICE ..jpg",
  "倒吊人": "THE HANGED MAN..jpg",
  "死神": "DEATH..jpg",
  "节制": "TEMPERANCE..jpg",
  "恶魔": "THE DEVIL •.jpg",
  "高塔": "THE TOWER..jpg",
  "星星": "THE STAR..jpg",
  "月亮": "THE MOON.jpg",
  "太阳": "THE SUN.jpg",
  "审判": "JUDGEMENT..jpg",
  "世界": "THE VYORLD..jpg",
  "权杖王牌": "w01.jpg",
  "权杖二": "w02.jpg",
  "权杖三": "w03.jpg",
  "权杖四": "w04.jpg",
  "权杖五": "w05.jpg",
  "权杖六": "w06.jpg",
  "权杖七": "w07.jpg",
  "权杖八": "w08.jpg",
  "权杖九": "w09.jpg",
  "权杖十": "w10.jpg",
  "权杖侍从": "w11.jpg",
  "权杖骑士": "w12.jpg",
  "权杖王后": "w13.jpg",
  "权杖国王": "w14.jpg",
  "圣杯王牌": "c01.jpg",
  "圣杯二": "c02.jpg",
  "圣杯三": "c03.jpg",
  "圣杯四": "c04.jpg",
  "圣杯五": "c05.jpg",
  "圣杯六": "c06.jpg",
  "圣杯七": "c07.jpg",
  "圣杯八": "c08.jpg",
  "圣杯九": "c09.jpg",
  "圣杯十": "c10.jpg",
  "圣杯侍从": "c11.jpg",
  "圣杯骑士": "c12.jpg",
  "圣杯王后": "c13.jpg",
  "圣杯国王": "c14.jpg",
  "宝剑王牌": "s01.jpg",
  "宝剑二": "s02.jpg",
  "宝剑三": "s03.jpg",
  "宝剑四": "s04.jpg",
  "宝剑五": "s05.jpg",
  "宝剑六": "s06.jpg",
  "宝剑七": "s07.jpg",
  "宝剑八": "s08.jpg",
  "宝剑九": "s09.jpg",
  "宝剑十": "s10.jpg",
  "宝剑侍从": "s11.jpg",
  "宝剑骑士": "s12.jpg",
  "宝剑王后": "s13.jpg",
  "宝剑国王": "s14.jpg",
  "星币王牌": "p01.jpg",
  "星币二": "p02.jpg",
  "星币三": "p03.jpg",
  "星币四": "p04.jpg",
  "星币五": "p05.jpg",
  "星币六": "p06.jpg",
  "星币七": "p07.jpg",
  "星币八": "p08.jpg",
  "星币九": "p09.jpg",
  "星币十": "p10.jpg",
  "星币侍从": "p11.jpg",
  "星币骑士": "p12.jpg",
  "星币王后": "p13.jpg",
  "星币国王": "p14.jpg"
};
  const result: Record<string, string> = {};
  Object.entries(mapping).forEach(([cardName, filename]) => {
    result[cardName] = `/images/tarot-cards/${encodeURIComponent(filename)}`;
  });
  return result;
}
